# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.TextField(default='jones'),
            preserve_default=False,
        ),
    ]
