# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0003_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddl.Menu')),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
    ]
