# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0004_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='food_item_id',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_item_ids',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddl.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='ddl.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddl.FoodItem'),
            preserve_default=False,
        ),
    ]
