# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0005_auto_20170504_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ddl.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, to='ddl.OrderItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ddl.FoodItem'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ddl.Menu'),
        ),
    ]
