# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0006_auto_20170504_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='menu',
        ),
    ]
