# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0007_remove_fooditem_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
