# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0008_remove_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_items', models.ManyToManyField(blank=True, to='ddl.OrderItem')),
            ],
            options={
                'db_table': 'order_cart',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddl.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddl.OrderCart'),
            preserve_default=False,
        ),
    ]
