# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0009_auto_20170505_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
            ],
            options={
                'db_table': 'address_table',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='has_checked_out',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddl.Address'),
            preserve_default=False,
        ),
    ]
