# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0010_auto_20170505_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
