# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0011_auto_20170505_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddl.Restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ddl.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
