# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0012_auto_20170505_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='special_instructions',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
