# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0013_orderitem_special_instructions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Consumer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='consumer',
        ),
        migrations.AlterModelTable(
            name='consumer',
            table='consumer',
        ),
    ]
